package com.asimio.demo.domain;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;

/**
 * FilmActorId generated by hbm2java
 */
@Embeddable
@Getter
@Setter
@EqualsAndHashCode
public class FilmActorId implements Serializable {

    private static final long serialVersionUID = 1L;

    @Column(name = "actor_id", nullable = false)
    private short actorId;

    @Column(name = "film_id", nullable = false)
    private short filmId;
}